server:
  port: 11004
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
logging:
  level:
    root: info
    com.yyq.data.secondly.repository: info
    com.yyq.data.secondly.service: info
    com.yyq.data.secondly.web: info